question_data = [
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "The song 'Megalovania' by Toby Fox made its third appearence in the 2015 RPG 'Undertale'.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "The Mann Co. Store from Team Fortress 2 has the slogan &quot;We hire mercenaries and get in fights&quot;.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
          "question": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Geography", "type": "boolean", "difficulty": "medium",
          "question": "Vietnam is the only country in the world that starts with V. ",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "Animals", "type": "boolean", "difficulty": "easy",
          "question": "A flock of crows is known as a homicide.", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
          "question": "Zero factorial is equal to zero. ", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "&quot;Foodfight!&quot; earned less than $80,000 at box office.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"category": "History", "type": "boolean", "difficulty": "medium",
          "question": "The Korean War ended in 1953 without any ceasefire.",
          "correct_answer": "False", "incorrect_answers": ["True"]}
]
